### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by travishathaway** [jamespacileo/django-pure-pagination#22]
I was recently using this repository with Python 3.3. I haven't fully tested it, but the only issue I had was with use of "xrange" [on line 181 of paginator.py](https://github.com/jamespacileo/django-pure-pagination/blob/master/pure_pagination/paginator.py#L181).

One possible way to fix this is adding something like this at the top of the file

```python
# Python 3
try:
    xrange
except(NameError):
    xrange = range
```

**Comment by slick666** [comment]
+1

**Comment by jlnabais** [comment]
+1

**Comment by jamespacileo** [comment]
@travishathaway @slick666 @jlnabais 

Better late than never... currently working with Python 3, thanks to contributors @lampslave 

If any of you use Docker, I've added the relevant files for firing up a Python 3 instance with Django 1.8+.

The fork added Travis CI tests which are cleverly testing against different versions of Python and Django (1.7, 1.8),
