### ISSUE TITLE
Maintained fork

### ISSUE THREAD

**Issue by jpic** [jamespacileo/django-pure-pagination#34]
Hi all, is there any maintained fork out there ?

Thanks !

**Comment by lampslave** [comment]
I maintain https://github.com/hovel/django-pure-pagination. I can't promise to resolve any issue, but if it will be relevant to our projects, I'll do it.

**Comment by jpic** [comment]
Nice ! do you think you could do a PyPi release since dependency_links is
deprecated now ?

**Comment by lampslave** [comment]
I don't see dependency_links in setup.py. Anyway you can install package directly from git...

**Comment by jpic** [comment]
On Sat, Dec 26, 2015 at 2:53 PM, lampslave <notifications@github.com> wrote:

> I don't see dependency_links in setup.py. Anyway you can install package
> directly from git...
>
That's exactly what I meant. Currently, if I want to pull in your fork in
my own setup.py, i have to do:

```
setup( # my app stuff...
    install_requires=[
        'django-pure-pagination==0.3.0',
    ],
    dependency_links=[
        '
https://github.com/hovel/django-pure-pagination/archive/master.tar.gz#egg=d
jango-pure-pagination-0.3.0',
    ]
)

```

But then, installing with pip:

```
$ pip install --process-dependency-links -Ue .
Obtaining file:///home/jpic/work/lqdn/political_memory
  DEPRECATION: Dependency Links processing has been deprecated and will be
removed in a future release.
```

So, I thought that it would be required to release it on PyPi to be able
for other apps to pull it as a dependency in setup.py, is there another way
?

**Comment by jpic** [comment]
On Sat, Dec 26, 2015 at 2:53 PM, lampslave <notifications@github.com> wrote:

> I don't see dependency_links in setup.py. Anyway you can install package
> directly from git...
>
That's exactly what I meant. Currently, if I want to pull in your fork in
my own setup.py, i have to do:

```
setup( # my app stuff...
    install_requires=[
        'django-pure-pagination==0.3.0',
    ],
    dependency_links=[
        'https://github.com/hovel/django-pure-pagination/archive/master.tar.gz#egg=django-pure-pagination-0.3.0',
    ]
)

```

But then, installing with pip:

```
$ pip install --process-dependency-links -Ue .
Obtaining file:///home/jpic/work/lqdn/political_memory
  DEPRECATION: Dependency Links processing has been deprecated and will be
removed in a future release.
```

( sorry for reposting, i forgot github wouldn't render markup when replying by email )

**Comment by lampslave** [comment]
Now I understand. Maybe http://stackoverflow.com/a/16624700 will help (see comments)?

**Comment by jamespacileo** [comment]
Hey guys,

Apologies for my disappearance, I can merge in iampslave changes.

Would that work?
Sounds like all outstanding fixes are included in his fork.

**Comment by jamespacileo** [comment]
I'll make it a priority to sort this out this evening after our big family
dinner is over.

Merry Christmas and/or happy holidays! 😄

**Comment by lampslave** [comment]
It would be great, but I'm not sure about compatibility. Probably you want to merge https://github.com/jamespacileo/django-pure-pagination/pull/32 first.

Have a nice day :)

**Comment by jamespacileo** [comment]
Hi @lampslave , wow the fork was pretty good.

I've merged it in! ...plus added a Dockerfile and docker-compose.yml for quickly spinning up the example.

I'll push it to PyPI as soon as I can.

**Comment by jamespacileo** [comment]
@lampslave @jpic latest version merged with Hovel fork pushed to PyPI

https://pypi.python.org/pypi/django-pure-pagination/0.3.0

**Comment by jpic** [comment]
Awesome, thanks !

**Comment by lampslave** [comment]
@jamespacileo 
I'm glad you liked it, thanks :)
